### ISSUE TITLE
Starters does not work

### ISSUE THREAD

**Issue by podabed** [ikhudo/gatsby-i18n-plugin#1]
@igorko/gatsby-plugin-lingui not found through yarn and npm. gatsby-plugin-lingui too. Please, fix starters.

**Comment by situplastik** [comment]
Totally agree. i18next example neither works.... After fixing the same issue of @podabed, the next error is:
`Error: Cannot find module '@babel/runtime/core-js/promise'`

**Comment by ikhudo** [comment]
Fixed
